Dev
Msawekho/To-Do-List pull request #1
Opened 2024-11-06 08:20 UTC by Msawekho

I created a to-do list that adds, remove/delete, search and mark completed tasks .

2024-11-06 09:08 UTC, MulamuMammba requested changes
@Msawekho Add the necessary connection between the frontend and backend

2024-11-06 09:08 UTC, MulamuMammba commented on public/index.html
>      </div>
# Use the node backend
@Msawekho from what I can see you are not utilizing the backend node server and doing everything on the fronend

2024-11-06 13:09 UTC, Msawekho commented on server.js
@ClementRep  is the linking correct for the node server?

2024-11-06 13:22 UTC, Ntlahla80 approved these changes

2024-11-06 13:22 UTC, Ntlahla80 commented on server.js
> +let tasks=[];
@Msawekho I see you have updated the node server.js nice job!!

2024-11-06 13:22 UTC, Ntlahla80 commented on public/style.css
>  }
@Msawekho I like how you have styled your front end nice job!!

2024-11-07 13:15 UTC, MulamuMammba approved these changes
I checked the improvements, looks good to me.

2024-11-08 09:58 UTC, ClementRep approved these changes

2024-11-13 12:24 UTC, merged